class FirebaseConstants {
  static const String usersCollection = 'users';
  static const String pronunciationCollection = 'pronunciations';
  static const String classroomsCollection = 'classrooms';
  static const String videoCollection = 'videos';

  static const String postCollection = 'posts';
  // static const String postsCollection = 'posts';
  // static const String commentsCollection = 'comments';
  // static const String likesCollection = 'likes';
  // static const String followersCollection = 'followers';
  // static const String followingCollection = 'following';
  // static const String notificationsCollection = 'notifications';
  // static const String messagesCollection = 'messages';
  // static const String chatsCollection = 'chats';
  // static const String chatMembersCollection = 'chatMembers';
  // static const String chatMessagesCollection = 'chatMessages';
  // static const String chatNotificationsCollection = 'chatNotifications';
  // static const String chatUnreadMessagesCollection = 'chatUnreadMessages';
  // static const String chatUnreadMessagesCountCollection = 'chatUnreadMessagesCount';
  // static const String chatTypingCollection = 'chatTyping';
  // static const String chatOnlineCollection = 'chatOnline';
  // static const String chatLastSeenCollection = 'chatLastSeen';
  // static const String chatMutedCollection = 'chatMuted';
  // static const String chatArchivedCollection = 'chatArchived';
  // static const String chatPinnedCollection = 'chatPinned';
  // static const String chatHiddenCollection = 'chatHidden';
  // static const String chatBlockedCollection = 'chatBlocked';
  // static const String chatReportedCollection = 'chatReported';
  // static const String chatDeletedCollection = 'chatDeleted';
  // static const String chatUsersCollection = 'chatUsers';
  // static const String chatUserRequestsCollection = 'chatUserRequests';
  // static const String chatUserRequestsSentCollection = 'chatUserRequestsSent';
  // static const String chatUserRequestsReceivedCollection = 'chatUserRequestsReceived';
  // static const String chatUserRequestsAcceptedCollection = 'chatUserRequestsAccepted';
  // static const String chatUserRequestsDeclinedCollection = 'chatUserRequestsDeclined';
  // static const String chatUserRequestsCancelledCollection = 'chatUserRequestsCancelled';
  // static const String chatUserRequestsBlockedCollection = 'chatUserRequestsBlocked';
  // static const String chatUserRequestsUnblockedCollection = 'chatUserRequestsUnblocked';
  // static const String chatUserRequestsReportedCollection = 'chatUserRequestsReported';
  // static const String chatUserRequestsDeletedCollection = 'chatUserRequestsDeleted';
  // static const String chatUserRequestsInvitedCollection = 'chatUserRequestsInvited';
  // static const String chatUserRequestsInvitedAcceptedCollection =
}
