// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOxrUkNQrZ_Um0KrAKJWiCemUas73QHtk',
    appId: '1:778736067261:android:d41eb9b2a82116f3b60dd4',
    messagingSenderId: '778736067261',
    projectId: 'movies-b232d',
    storageBucket: 'movies-b232d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD7zZcd2xc_UAqUo7QQZyXE7DNQ-yBQ-g',
    appId: '1:778736067261:ios:eb0a33751142ce06b60dd4',
    messagingSenderId: '778736067261',
    projectId: 'movies-b232d',
    storageBucket: 'movies-b232d.appspot.com',
    androidClientId: '778736067261-52rkicgch2sch068reluvc8v6mcjob91.apps.googleusercontent.com',
    iosClientId: '778736067261-nl7aneh3bsirdp42mn6c7hhsh1l1it27.apps.googleusercontent.com',
    iosBundleId: 'com.agnibha.languageLearningApp',
  );
}
